spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-sell/config.git
          username: m15527185733@163.com
          password: gzc15527185733
#          basedir: G:\edu\cczhilie\springCloud-Cell\config-basedir
  rabbitmq:
    host: 192.168.1.103
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.103:8762/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.103
    instance-id: ${eureka.instance.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
